/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolkitRouteImport } from './routes/toolkit'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as EducationRouteImport } from './routes/education'
import { Route as IndexRouteImport } from './routes/index'

const ToolkitRoute = ToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/toolkit': typeof ToolkitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/toolkit': typeof ToolkitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/toolkit': typeof ToolkitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/education' | '/experience' | '/projects' | '/toolkit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/education' | '/experience' | '/projects' | '/toolkit'
  id: '__root__' | '/' | '/education' | '/experience' | '/projects' | '/toolkit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EducationRoute: typeof EducationRoute
  ExperienceRoute: typeof ExperienceRoute
  ProjectsRoute: typeof ProjectsRoute
  ToolkitRoute: typeof ToolkitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EducationRoute: EducationRoute,
  ExperienceRoute: ExperienceRoute,
  ProjectsRoute: ProjectsRoute,
  ToolkitRoute: ToolkitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
